name: Capstone-Microsoft
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  - black
  - flake8
  - isort
  - loguru
  - numpy
  - pandas
  - planetary-computer
  - rioxarray
  - stackstac
  - tqdm
  - typer
  - xarray
  - pip:
    - python-dotenv
    - mkdocs
    - -e .