name: Capstone-Microsoft
channels:
  - conda-forge
dependencies:
  - python=3.9
  - pip
  - typer
  - loguru
  - tqdm
  - black
  - flake8
  - isort
  - xarray
  - rioxarray
  - planetary-computer
  - stackstac
  - pip:
    - python-dotenv
    - mkdocs
    - -e .